language: generic
sudo: false

install:
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/2019-06-12T11.56.27Z.emacs-bin-26.tar.gz
  - tar -xaf 2019-06-12T11.56.27Z.emacs-bin-26.tar.gz -C /
  # Configure $PATH: Emacs installed to /tmp/emacs
  - export PATH=/tmp/emacs/bin:${PATH}
  # Install dependencies for older Emacs versions which lack them.
  # Introduced in Emacs 24.3.
  - if ! emacs -Q --batch --eval "(require 'cl-lib)" ; then
        curl -Lo cl-lib.el http://elpa.gnu.org/packages/cl-lib-0.6.1.el ;
    fi
  # Introduced in Emacs 24.1
  - if ! emacs -Q --batch --eval "(require 'ert)" ; then
        curl -LO https://raw.githubusercontent.com/ohler/ert/c619b56c5bc6a866e33787489545b87d79973205/lisp/emacs-lisp/ert.el &&
        curl -LO https://raw.githubusercontent.com/ohler/ert/c619b56c5bc6a866e33787489545b87d79973205/lisp/emacs-lisp/ert-x.el ;
    fi

script:
  - ldd $(which emacs)
  - emacs --version
  - emacs --batch --eval '(print libgnutls-version)'
  - emacs --batch --eval '(princ (gnutls-available-p))'


